module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-max-line-length': [2, 'always', 100],
    'subject-case': [2, 'always', ['lower-case']],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'build',
        'revert',
        'security',
        'hotfix',
        'wip',
        'experiment',
        'merge',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'api',
        'ui',
        'db',
        'config',
        'deps',
        'ci',
        'validation',
        'i18n',
        'analytics',
        'middleware',
        'logging',
        'storage',
        'caching',
        'queue',
        'search',
        'payment',
        'notification',
        'migration',
        'monitoring',
        'docker',
        'seo',
        'accessibility',
        'graphql',
        'websocket',
      ],
    ],
  },
};
